### ISSUE TITLE
Generated bind volume must be prefixed with ./

### ISSUE THREAD

**Issue by moufmouf** [theaentmachine/aent-docker-compose#44]
When installing PHP image, we get:

```
    volumes:
    - type: bind
      source: api
      target: /var/www/html
```

This causes an error with Docker-compose that expects a ./ like this:

```
    volumes:
    - type: bind
      source: ./api
      target: /var/www/html
```
